export const Top = [
  {
    _id: 1,
    name: "Pink Top",
    price: 50.67,
    rating: 4,
    img: require("../../assets/pinktop.png"),
    isFavorite: false,
  },
  {
    _id: 2,
    name: "Men Polo Shirt",
    price: 59.6,
    rating: 4.5,
    img: require("../../assets/menpolo.png"),
    isFavorite: false,
  },
  {
    _id: 3,
    name: "Men's Shirt",
    price: 69.77,
    rating: 5,
    img: require("../../assets/men6.png"),
    isFavorite: false,
  },

  {
    _id: 4,
    name: "Purple Top",
    price: 70.0,
    rating: 2.5,
    img: require("../../assets/purple.png"),
    isFavorite: false,
  },
  {
    _id: 5,
    name: "Trendy Men's Tee",
    price: 45.89,
    rating: 3.5,
    img: require("../../assets/men5.png"),
    isFavorite: false,
  },
  {
    _id: 6,
    name: "Sleeveless Sweat Shirt",
    price: 67.99,
    rating: 3.5,
    img: require("../../assets/Men2.png"),
    isFavorite: false,
  },
  {
    _id: 7,
    name: "Trendy Men's Shirt",
    price: 45.89,
    rating: 3.5,
    img: require("../../assets/muroon-shirt.jpeg"),
    isFavorite: false,
  },
  {
    _id: 8,
    name: "Women Tee",
    price: 67.99,
    rating: 3.5,
    img: require("../../assets/women3.png"),
    isFavorite: false,
  },
  {
    _id: 9,
    name: "Women's Jacket",
    price: 45.89,
    rating: 3.5,
    img: require("../../assets/women4.png"),
    isFavorite: false,
  },
  {
    _id: 10,
    name: "Green Shirt",
    price: 67.99,
    rating: 3.5,
    img: require("../../assets/green-shirt.jpeg"),
    isFavorite: false,
  },
  {
    _id: 11,
    name: "Men's Shirt",
    price: 67.99,
    rating: 3.5,
    img: require("../../assets/shirt1.png"),
    isFavorite: false,
  },
];
