export const Bottoms = [
  {
    _id: 1,
    name: "Men's Shorts",
    price: 50.67,
    rating: 4,
    img: require("../../assets/men1.png"),
    isFavorite: false,
  },
  {
    _id: 2,
    name: "Puple Shorts",
    price: 59.6,
    rating: 4.5,
    img: require("../../assets/pupleb.png"),
    isFavorite: false,
  },
  {
    _id: 3,
    name: "Sweat Pants",
    price: 69.77,
    rating: 5,
    img: require("../../assets/white-trouser.jpeg"),
    isFavorite: false,
  },

  {
    _id: 4,
    name: "Cotton Shorts",
    price: 70.0,
    rating: 2.5,
    img: require("../../assets/men4.png"),
    isFavorite: false,
  },
  {
    _id: 5,
    name: "Pink Bottoms",
    price: 45.89,
    rating: 3.5,
    img: require("../../assets/pinkbottom.png"),
    isFavorite: false,
  },
  {
    _id: 6,
    name: "Long Tights",
    price: 67.99,
    rating: 3.5,
    img: require("../../assets/mentights.png"),
    isFavorite: false,
  },
  {
    _id: 7,
    name: "Short Tights",
    price: 45.89,
    rating: 3.5,
    img: require("../../assets/stight.png"),
    isFavorite: false,
  },
  {
    _id: 8,
    name: "Elastic Pants",
    price: 45.89,
    rating: 3.5,
    img: require("../../assets/womenb.png"),
    isFavorite: false,
  },
];
