export const product = [
  {
    _id: 1,
    name: "Workout OUTFIT",
    price: 50.67,
    rating: 4,
    img: require("../../assets/black-outfit.jpeg"),
    isFavorite: false,
  },
  {
    _id: 2,
    name: "Leather Jacket",
    price: 69.77,
    rating: 5,
    img: require("../../assets/brown-jacket.jpeg"),
    isFavorite: false,
  },
  {
    _id: 3,
    name: "White Trouser",
    price: 59.6,
    rating: 4.5,
    img: require("../../assets/white-trouser.jpeg"),
    isFavorite: false,
  },
  {
    _id: 4,
    name: "Mehroon T-shirt",
    price: 70.0,
    rating: 2.5,
    img: require("../../assets/muroon-shirt.jpeg"),
    isFavorite: false,
  },
  {
    _id: 5,
    name: "Sports Jacket",
    price: 45.89,
    rating: 3.5,
    img: require("../../assets/grey-jacket.jpeg"),
    isFavorite: false,
  },
  {
    _id: 6,
    name: "White Outfit",
    price: 67.99,
    rating: 3.5,
    img: require("../../assets/white-outfit.jpeg"),
    isFavorite: false,
  },

  {
    _id: 7,
    name: "Sports T-shirt",
    price: 56.87,
    rating: 4,
    img: require("../../assets/green-shirt.jpeg"),
    isFavorite: false,
<<<<<<< HEAD
  },
  {
    _id: 8,
    name: "Unisex Tracksuit",
    price: 80.8,
    rating: 4,
    img: require("../../assets/track.png"),
    isFavorite: false,
  },
  {
    _id: 9,
    name: "Adidas Track Top",
    price: 50.0,
    rating: 4,
    img: require("../../assets/adidastracksuit.png"),
    isFavorite: false,
  },
  {
    _id: 10,
    name: "Sweat Shirt",
    price: 30.87,
    rating: 4,
    img: require("../../assets/shirt1.png"),
    isFavorite: false,
=======
>>>>>>> f516531e1e31bc7f42f1c894e5c1144a9b1bebc1
  },
];
